### ISSUE TITLE
hcp orient 

### ISSUE THREAD

**Issue by mastricker** [pierrehirel/atomsk#13]
Hi,

thank you very much for this package. I have a question regarding the reorientation of the hcp lattice. Your documentation [here](http://atomsk.univ-lille1.fr/doc.php) states that the (HKIL) vectors of the hcp convention are not supported.
But since they are redundant anyways, I was wandering if it is possible to rotate a hcp lattice with the reduced set, i.e. (HKIL) -> (HKL), since I = -(H+K). Some other packages, like the atomic simulation environment do that. They rotate a structure regardless of the underlying symmetry.

My command is the following:
```
atomsk -nthreads 1 --create hcp 3.187 5.197997 Mg -orthogonal-cell -orient [020] [-102] [100] -duplicate 20 1 5  mg_cell.xsf
```
But nothing is rotated
Even making it in two steps, does not result in a rotation:
```
atomsk -nthreads 1 --create hcp 3.187 5.197997 Mg -orthogonal-cell -duplicate 3 5 2  mg_cell.xsf
atomsk mg_cell.xsf -nthreads 1 -orient [2-10] [-120] [001] [2-10] [241] [-102] final.xsf
```
What I basically want is to rotate the crystal around the x-axis  ~27 degrees and the mirror it.
The error message reads:
```
 X!X ERROR: the base Hend is not a rotation of Hstart.
     Check that angles are equal in Hstart and Hend.
```
and I don't know what do do with that.
Thanks,
Markus

Edit: I just wanted to add that I want to create a hcp twin boundary. Maybe there is an easier way, but it is not obvious to me.

**Comment by pierrehirel** [comment]
Dear sir,

If you are using the master version from Gitlab (I assume you do since you're writing in here), then it does support [hkil] notation, both in the mode "--create", and when using the option "-orient".

It is possible to orient hcp lattices directly in the mode "--create", for example:

`atomsk --create hcp 3.187 5.197997 Mg orient [02-20] [-1012] [10-10]  mg_cell.xsf`

See the tutorial related to that: [http://atomsk.univ-lille1.fr/tutorial_orient.php]

Then, the option "-orient" requires you to provide the initial crystal orientation, and the final orientation. In your first example you only provide one orientation, so some information is missing (I should modify the code so that it complains about that).

If you know the angle of rotation, you can also use the option "-rotate" instead.

Best regards

**Comment by mastricker** [comment]
Hello,

thank you very much. I have solved it differently now. I used the orthogonal cell with polycrystal option.

Thanks!
Markus
