### ISSUE TITLE
atomsk `orient` doewsn't work if the working directory contains another directory named 1 or 2 !

### ISSUE THREAD

**Issue by sphCow** [pierrehirel/atomsk#19]
I came across this ghostly bug with atomsk. To reproduce do the following: 

create an empty directory and execute for example

`atomsk --create fcc 1.386720 Al orient [1-21] [10-1] [111] -duplicate 7 14 7 -ow e_0.0370_h_-44_lat.xsf`

this perfectly works. Now do 

`mkdir 1 && atomsk --create fcc 1.386720 Al orient [1-21] [10-1] [111] -duplicate 7 14 7 -ow e_0.0370_h_-44_lat.xsf`

or 

`mkdir 2 && atomsk --create fcc 1.386720 Al orient [1-21] [10-1] [111] -duplicate 7 14 7 -ow e_0.0370_h_-44_lat.xsf`

in this case atomsk says: 

`X!X ERROR: base vectors are not orthogonal.`

The logfile points out that the arguments of orient are not being interpreted properly. In the first case the logfile is perfect 

```
debug: Command-line arg #  5   : orient  
debug: Command-line arg #  6   : [1-21]  
debug: Command-line arg #  7   : [10-1]  
debug: Command-line arg #  8   : [111]
```

But in the second case it reads

```
debug: Command-line arg #  5   : orient  
debug: Command-line arg #  6   : 1  
debug: Command-line arg #  7   : 1  
debug: Command-line arg #  8   : 1  
```

**Comment by pierrehirel** [comment]
Dear Sir,

Thank you for reporting this, it is an interesting point. The issue does not come from Atomsk, but from the expansion of the shell (bash or other). To convince you, do the following experiment:

- create a directory named 1;
- use "echo" before the Atomsk command to see what command is actually executed; you will see the following:

`echo atomsk --create fcc 1.386720 Al orient [1-21] [10-1] [111] -duplicate 7 14 7 -ow e_0.0370_h_-44_lat.xsf`

It will print the command that is actually run after shell expansion:

`atomsk --create fcc 1.386720 Al orient 1 1 1 -duplicate 7 14 7 -ow e_0.0370_h_-44_lat.xsf`

Here is what happens: because a folder named "1" exists, the shell (bash) expands the braces into file names (or folder names): [1-21] becomes 1, and the same happens with [1-10] and [111]. More generally, if a number inside the brackets match the name of an existing file or folder, then the whole bracket is replaced by that file or folder's name. This behaviour is described in the bash manual:

[https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html#Filename-Expansion](https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html#Filename-Expansion)

So, at the moment when Atomsk is actually executed, it receives the arguments "1 1 1" -and tells you that something is wrong.

A simple solution is to delete the folder named "1" before running Atomsk. Another solution is to remove the brackets and run the command like this:

`atomsk --create fcc 1.386720 Al orient 1-21 10-1 111 -duplicate 7 14 7 -ow e_0.0370_h_-44_lat.xsf`

No brackets, therefore no shell expansion, and Atomsk will receive the correct arguments.

I hope this helps you

Best regards

**Comment by sphCow** [comment]
Thank you for your detailed explanation. I completely agree that shell expansion is causing this issue and nothing to do with atomsk itself. And also thanks for suggesting simple workarounds.
