### ISSUE TITLE
Issues with orientation and conversion to JEMS

### ISSUE THREAD

**Issue by JulioAzcarate** [pierrehirel/atomsk#21]
Dear Pierre Hirel

First of all, congratulation on the creation of Atomsk. It's a great tool to create and manipulate crystal structures!!!

**First Issue**
I fund some issues trying crystal orientation. I need to create a c14 precipitate of ZrNbFe2 inner a Z matrix to simulate HRTEM image with JEMS. In C14 structure I remove the Fe in position 000 and 001/2 and replace by Nb. That works very well. The normal orientation given by atomsk was:

> ..> C14 ZrFe2 with box vectors H1=[2-1-10], H2=[-12-10], H3=[0001].
 ..> System was successfully created.
>
However, when I try to reorient the crystal it doesn't work:

 `atomsk C14-creado.cfg -orient [2-1-10] [-12-10] [0001] [-1011] [1-101] [01-11] C14-rotada.cfg`

 >>> Opening the input file: C14-creado.cfg
 ..> Input file was read successfully (12 atoms).
 >>> Rotating the system to change the crystal orientation...
 X!X ERROR: the base Hend is not a rotation of Hstart.
     Check that angles are equal in Hstart and Hend.
 X!X ERROR: there were errors while applying options.
 \o/ Program terminated successfully!
     Total time: 0.003 s.; CPU time: 0.003 s.

I don't understand is I made a mistake or if is an issue in "orient" calculation with a hexagonal base.

**Second Issue**
I replete the example from the tutorial about Crystal Orientation:
`atomsk --create bcc 2.85 Fe Fe.cfg`
and then
`atomsk Fe.cfg -orient [100] [010] [001] [121] [-101] [1-11] Fe_orient.cfg`
I checked with Ovito that the re-orientation work pretty well. However, when I converted both files to JEMS's input files
`atomsk Fe.cfg -unit A nm JEMS` and `atomsk Fe_orient.cfg -unit A nm JEMS` both files were rendered in the same orientation by JEMS ([001] axis zone)

Thank you in advance

**Comment by pierrehirel** [comment]
Dear Julio,

I think you misunderstand how the option "-orient" works. It does not create a new cell with different crystal orientation. It only rotates the crystal (similar to what you could obtain by using the option "-rotate"), so that the crystal axes are changed to the target orientation. As a result, the box vectors are not aligned any more with the Cartesian axes, as you can visualize in OVITO.

With that in mind, here are the answers to your questions:

**First issue**
I think the message "ERROR the base Hend is not a rotation of Hstart" is quite clear: the target orientation that you want (that is H1=[-1011], H2=[1-101], H3=[01-11]) is not a rotation of the original crystal directions (H1=[2-1-10], H2=[-12-10], H3=[0001]). In other words, you can not go from one to the other with a rotation matrix, so Atomsk cannot do what you want.

**Second issue**
In JEMS the cell vectors are not written in full. What is written is simply the length of each box vector, and the angle between them (see the lines starting with "lattice"). Therefore, the information that the system was rotated is lost. This is why JEMS displays exactly the same thing, whether you rotated the system beforehand or not. This is a shortcoming of the JEMS file format, not of Atomsk.

Now, with that said, what are the solutions to your problems?

**First issue**
Instead of rotating the system after it is created, ask for the target orientation directly as part of the mode "--create", like the following:

`atomsk --create c14 4 3 Zr Fe orient [-1011] [1-101] [01-11] ZrFe2.cfg`

Second issue
Same idea:

`atomsk --create bcc 2.85 Fe orient [121] [-101] [1-11] Fe_orient.cfg`

I hope this helps you understand how Atomsk works and how to construct your atomic systems.

Best regards

**Comment by JulioAzcarate** [comment]
Dear Pierre

Thank you so much!!! ... Very clear.
We partially solve our problem converting the hexagonal lattice to orthorhombic. Really, we need to create a c14 lattice of ZrNbFe (were the half of Fe in ZrFe2 are replaced by Nb ... I'll create other threads whit the proper question) 
Now wee need to find the proper index in the new lattice!

Best regards

**Comment by pierrehirel** [comment]
Since there are no more questions in this thread I close the issue.
