### ISSUE TITLE
Atom missing when constructing hcp-Mg polycrystal

### ISSUE THREAD

**Issue by XINGZheyuan-SWJTU** [pierrehirel/atomsk#32]
Dear Sir,

I was trying to construct an atomic model of hcp-Mg polycrystal with the command polycrystal in Atomsk. I read the tutorial and used the following command:

atomsk --create hcp 3.2 5.225 Mg Mg.xsf
atomsk --polycrystal Mg.xsf poly.txt final.cfg -wrap

with file poly.txt containing:

box 600 600 600
random 8

But the output file seems bizarre because some atoms are missing at the grain boundary. As shown in this picture:
![image](https://user-images.githubusercontent.com/33805270/124572096-f4d66600-de7a-11eb-870c-76da880ed72e.png)
 A cavity exists at the grain boundary in the interior of the model. I have tried the same commands serval times, although the generated models are different, the cavity always exists.

I read the Issue#28 which seems to have the same problem, so I tried to do the same thing on a different computer. But I still have the same problem.

The version of the first computer is:

Windows 10 Home edition
Atomsk Version Beta-0.10.6
![image](https://user-images.githubusercontent.com/33805270/124575304-dcb41600-de7d-11eb-9ece-dd93b302cd25.png)

The version of the second computer is:

Ubuntu 18.04.1
Atomsk Version Beta-0.11

I found that changing the version of Atomsk or Operating System did not fix the problem.

Thank you!

**Comment by pierrehirel** [comment]
Dear Sir,

Thank you for reporting this problem. It took me a few days to figure it out. It comes from the fact that the seed (unit cell) is not duplicated enough times to cover the entire grain, because it is not orthogonal. Here the seed is hexagonal (hcp Mg), hence Atomsk does not compute properly the duplication factor to create the grains.

First, I would like to point out that Atomsk can transform an hexagonal crystal into an orthogonal cell. When creating your seed, use the option "-orthogonal-cell" like this:

`atomsk --create hcp 3.2 5.225 Mg  -orthogonal-cell  Mg.xsf`

If you do this the seed is orthogonal, and you will not have voids in your polycrystal.

Second, I modified the code so it should correctly fill the grains even if the seed is not orthogonal. You can try the new version by downloading the latest master version from GitHub. If you do, I would appreciate if you could confirm that it solves your problem.

Best regards

**Comment by pierrehirel** [comment]
Without further response for more than a month I close this issue.
