### ISSUE TITLE
lmp file has no pair coefficient generated from cif file

### ISSUE THREAD

**Issue by jiamingl98** [pierrehirel/atomsk#34]
For lammps file generation, the lmp output file do not have pair coefficients.

Output file:
LAMMPS (7 Aug 2019)
units		real
dimension       3
atom_style	charge
boundary        p p p

pair_style      lj/cut    12.0
#bond_style      harmonic
#angle_style     cosine/periodic
#dihedral_style  harmonic
pair_modify     tail yes mix arithmetic
#special_bonds   lj/coul 0.0 0.0 1.0

read_data       1525727.lmp
  orthogonal box = (0 0 0) to (32.49 32.49 25.78)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  1500 atoms
  read_data CPU = 0.00899792 secs
variable        dt         equal 1.00
variable        tdamp      equal 100*${dt}
variable        tdamp      equal 100*1
fix             1 all langevin 298.00 298.00 ${tdamp} 2907865
fix             1 all langevin 298.00 298.00 100 2907865
fix             2 all nve
thermo          0
run             1000
ERROR: All pair coeffs are not set (../pair.cpp:230)
Last command: run             1000

**Comment by pierrehirel** [comment]
Sir,

A simple "hello" when starting a discussion is always appreciated.

As you can see from your log file, LAMMPS reads perfectly the data file:

`read_data 1525727.lmp
orthogonal box = (0 0 0) to (32.49 32.49 25.78)
1 by 1 by 1 MPI processor grid
reading atoms ...
1500 atoms`

The error message is not related to the input data file. The error message is: "**All pair coeffs are not set**", and it is produced by the module "pair.cpp". This is a clear indication that the error comes from your definition of the potential parameters, apparently because you have no "pair_coeff" line.

If you had typed the error message in Google, you would have found multiple threads in the LAMMPS forum discussing this type of error.

Since this discussion is unrelated to Atomsk I close this thread. I recommend that you ask your questions to the LAMMPS community.

Regards
