### ISSUE TITLE
Feature request: Option to convert file containing several snapshots to another format

### ISSUE THREAD

**Issue by rashidrafeek** [pierrehirel/atomsk#36]
Thanks for developing this great package. It has been very useful in my work. 

It is currently possible to convert a file containing many snapshots to several file using the `--one-in-all` option and also to convert many files into one file containing all snapshots using the `all-in-one` option. It would be nice to have an option to convert a file containing several snapshots to another format which can contain several formats, instead of writing to separate files. My use case is to convert a LAMMPS dump file to animated xsf file or extended xyz file.

I currently use the workaround of first converting the file to several files using `one-in-all` option and then converting all the separate files to one using the `all-in-one` option and then delete the intermediate files. But it would be great if it is possible to do this directly in atomsk.

**Comment by pierrehirel** [comment]
Dear Sir,

As you mention it is already possible to do what you ask with Atomsk. You have to convert the initial file into separate files with the mode "--one-in-all", and then convert all these files into a single file with the mode "-all-in-one".

Of course it would be possible to merge those two steps into one, which would require developing a new mode. I will not do it personally because: 1) Atomsk can already do it, 2) I do not have the time.

If you (or someone else) develops this mode I will consider to include it in Atomsk.

Best regards

**Comment by rashidrafeek** [comment]
I don't have experience coding in Fortran and I'm not sure I would be able to implement this feature. But I will give it a try. Thanks for the response.

Regards.
