### ISSUE TITLE
Ternary alloy supercell

### ISSUE THREAD

**Issue by Karthik9805** [pierrehirel/atomsk#39]
I am trying to create a fcc ternary alloy supercell using Atomsk 
While It allows me to make binary alloys,  the program doesn't allow me to have three or more components?
Is there a workaround? 

Thanks

**Comment by pierrehirel** [comment]
Dear Sir,

The fcc unit cell counts 4 atoms. In the mode "--create" it is only possible to create a fcc lattice with one or two elements. These two possibilities are defined unambiguously (2 atoms of the first element, 2 atoms of the second).

If you wish to have 3 different elements in an fcc lattice, then this is not defined unambiguously and depends on what you want to do. If you wish to create a unit cell of the fcc lattice with different elements, I suggest that you begin by creating a unit cell with a single element, for example:

`atomsk --create fcc 4.01 Ni Ni.xsf`

Then, open the file "Ni.xsf" with a text editor and modify the elements. This is rather quick because this file contains only 4 atoms.

However most of the time, ternary alloys are not defined by repeating a unit cell containing the 3 elements, but by random substitution in an fcc lattice. To achieve that, duplicate an fcc lattice, and then use a combination of options "-select random" and "-substitute". Here is a simple example:

`atomsk --create fcc 4.02 Ni -duplicate 10 10 10 -select random 40% Ni -substitute Ni Fe -select random 50% Fe -substitute  Fe Cr final.cfg`

In this example, the final file will contain 60% Ni, 20% Fe and 20% Cr.

I hope these suggestions help you construct your atomic system.

Best regards

**Comment by Karthik9805** [comment]
Thanks for your response. It was useful

Best Regards,
Karthik

________________________________
