### ISSUE TITLE
Problems with VASP OUTCAR in mode --one-in-all

### ISSUE THREAD

**Issue by kluophysics** [pierrehirel/atomsk#43]
I had troudble in converting vasp output. I noticed in old closed issues, people were able to use QE. So I tried to use QE output in --one-in-all mode and it worked smoothly. I'm wondering what might go wrong. Thanks in advance!

```
$ atomsk --one-in-all OUTCAR 
  ___________________________________________________
 |              ___________                          |
 |     o---o    A T O M S K                          |
 |    o---o|    Version b0.11.2                      |
 |    |   |o    (C) 2010 Pierre Hirel                |
 |    o---o     https://atomsk.univ-lille.fr         |
 |___________________________________________________|
 *** Working out of office hours? You should sleep sometimes. :-)
 >>> Unfolding OUTCAR to many files...
 X!X ERROR: there were errors while reading the file:
 >>> No file was converted.
 \o/ Program terminated successfully!
     Total time: 0.002 s.; CPU time: 0.002 s.
```

**Comment by pierrehirel** [comment]
Dear Sir,

As stated in the documentation:
[https://atomsk.univ-lille.fr/doc/en/format_outcar.html](https://atomsk.univ-lille.fr/doc/en/format_outcar.html)

"Note that the OUTCAR file contains several configurations, **only if VASP performed ionic relaxation or molecular dynamics** (IBRION≥0). Otherwise, it only contains information about electronic states which Atomsk does not support."

If you used IBRION≥0 in your simulation, and Atomsk cannot read it, then it may be a bug. Please send your OUTCAR file so I can investigate.

If you used IBRION=-1, then your OUTCAR file contains only information about the electronic structure, and it is normal that Atomsk cannot read it. If you wish, you may still convert the CONTCAR file with: "atomsk CONTCAR cfg" (for example).

Best regards

**Comment by pierrehirel** [comment]
In the absence of response or comment for more than a month, I close this thread.

**Comment by kluophysics** [comment]
[OUTCAR.log](https://github.com/pierrehirel/atomsk/files/9531450/OUTCAR.log)
[INCAR.log](https://github.com/pierrehirel/atomsk/files/9531452/INCAR.log)


Sorry for the delayed reply! In order to reduce the size of the outcar file, I only kept first 30 frames of the md run. The INCAR for this md run is also included. Note a suffix .log is appended for github uploading. I'd appreciate if you can look into this matter.

**Comment by pierrehirel** [comment]
Thanks for the files, I was able to identify the problem. Actually I identified two problems, one that occurred because the keyword "IBRION" appeared in a comment in the OUTCAR file, and another one where the lattice vectors coud not be read.

I have just pushed an updated version. Can you please try the latest version from GitHub and confirm if it fixes your problems?

**Comment by pierrehirel** [comment]
In the absence of response or comment for more than a month, I close this thread.
