### ISSUE TITLE
BCC polycrystals with elongated grains contain a lot of non-BCC atoms

### ISSUE THREAD

**Issue by jfikar** [pierrehirel/atomsk#8]
Hello,
I'm trying to produce BCC polycrystals with 12 randomly oriented grains largely elongated in Z direction (at least 1:10 or higher ratio).

In this case "random 12" does not seem to work, as it somehow tends to produce almost equiaxed grains. I have tried 12 prismatic grains with hexagonal base. First approximately equiaxed:

poly.txt:

box 134.7 116.6 50
node 0.125*box 0.0000*box 0.5*box random
node 0.125*box 0.3333*box 0.5*box random
node 0.125*box 0.6667*box 0.5*box random

node 0.375*box 0.1667*box 0.5*box random
node 0.375*box 0.5000*box 0.5*box random
node 0.375*box 0.8333*box 0.5*box random

node 0.625*box 0.0000*box 0.5*box random
node 0.625*box 0.3333*box 0.5*box random
node 0.625*box 0.6667*box 0.5*box random

node 0.875*box 0.1667*box 0.5*box random
node 0.875*box 0.5000*box 0.5*box random
node 0.875*box 0.8333*box 0.5*box random

Then I run:

atomsk --create bcc 3.1652 W xsf
atomsk --polycrystal W.xsf poly.txt poly.lmp -wrap

Then the I open the resulting file in Ovito and run Structure Identification > Common Neighbor Analysis (you can use Ackland-Jones or VoroTop, results are the same), it finds approximately 70% BCC atoms. This seems reasonable.

Then I stretch the box 10 times in Z:
box 134.7 116.6 500

and  in this case Ovito finds only about 30% BCC atoms. The non-BCC are on top and down on each hexagonal column. I understand there is a problem on the PBC in Z direction, but I somehow thought, there will be just a small number of disordered atoms, not the majority of them.

In atomsk manual there is also 2D polycrystal produced by specifying 0 in Z direction:
box 134.7 116.6 0

That works well, about 75% of BCC atoms, but I have all the grains oriented <100> in the Z direction.

Is there any other way to produce randomly oriented elongated grains?

**Comment by pierrehirel** [comment]
Dear jfikar,

First, if all grains have a random rotation, then it is not possible to satisfy the periodicity along Z for all of them. But I think you figured that out already.

Second, there is a problem with the Voronoi construction when grains are exaggeratedly elongated. For each node, the program looks for neighbouring nodes, and cuts them at half the node-node distance. 3-D periodic boundary conditions are assumed, which means that periodic replicas of nodes are also taken into account. In your case, periodic replicas are responsible for cutting the central grains at different locations and with various angles, resulting in strange and non-physical structures.

The solution would be to add an option to take only neighbours along Z into account. I will see what I can do in this regard.

**Comment by jfikar** [comment]
Dear Pierre,

thank you for your fast answer. I'm not completely sure, what is causing the problem, but maybe an option ti switch off the periodicity along Z will help, while keeping the periodicity in X and Y. There certainly will be a mismatched layer of atoms on the top and bottom surfaces, but probably less important than now. And such sample could also be used with PBC switched off in Z direction in the simulations. Is this what you propose?

**Comment by pierrehirel** [comment]
On the contrary, the problem came from the fact that periodic replica of the nodes along Z are not taken into account.

I just committed a modified version. Now, periodic replica of the current node are ALWAYS taken into account (in addition to neighboring nodes of course). This should solve your problem. Please compile latest version from Github and let me know if it works.

**Comment by jfikar** [comment]
Dear Pierre, thank you very much. The new version of atomsk looks indeed better. For my example with box height 500A I get now 75% of BCC atoms instead of 30% with the old version. This seems to be reasonable. However, I've found two new issues:

(A)
I tried to exaggerate the box height even more to 2500A and here the result is quite strange. The grains do not fill the box in the upper part. The bottom part looks fine though. The grains end at heights from 1600-2200A, every grain at different height. The box contains 1.988 millions of atoms, but should contain more. Warning, you would need a lot of RAM to reproduce it. The new code needs approximately 90GB, the old code seems to need only half 45GB RAM. The old code fills the same box with 2.891millions of atoms, but has the disordered regions in top and bottom parts.

(B)
I was not happy with all grains ending exactly at the bottom and top box boundary. So I tried what happens, if my nodes are not exactly in one plane, but I move them slightly randomly up and down. For example:

box 134.7 116.6 500
node 0.125*box 0.0000*box 0.491*box random
node 0.125*box 0.3333*box 0.474*box random
node 0.125*box 0.6667*box 0.470*box random

node 0.375*box 0.1667*box 0.521*box random
node 0.375*box 0.5000*box 0.468*box random
node 0.375*box 0.8333*box 0.502*box random

node 0.625*box 0.0000*box 0.480*box random
node 0.625*box 0.3333*box 0.496*box random
node 0.625*box 0.6667*box 0.543*box random

node 0.875*box 0.1667*box 0.472*box random
node 0.875*box 0.5000*box 0.450*box random
node 0.875*box 0.8333*box 0.541*box random

The result with the new code has again disordered region of atoms on the bottom and on the top of the sample. The thickness of the new disordered region is approximately equal to the scatter I introduced in the z coordinates of the nodes.

**Comment by pierrehirel** [comment]
OK, glad to see it solved the original problem. Now for the new issues:

(A) The code generates a very large template grain, based on the size of the final cell. Then this template is rotated and cut to form each grain. Since each grain has a random rotation, there is no simple way to determine the "best" duplication factor that is suitable for all grains, so the seed is just duplicated according to the maximum box length in all directions. This method uses more RAM, but is more CPU-efficient than duplicating a seed for each grain. To solve the initial problem I already had to increase the size of this template grain, that's why the new version uses more RAM. Now with a box size of 2500 angströms, what you see comes from the fact that the template grain is not large enough, hence the grains seem to be "cut". The only way to solve this is to increase again the size of the template grain, but I am afraid this will increase the memory usage by a lot.

(B) When you move the positions of nodes along Z, you may expect that the grains "glide" along that direction. This is not what happens. If the nodes are not on the same level along Z, then the GB planes between them (the vertices) will not be vertical, but will be inclined, which results in the strange, disordered regions that you see. I think it this cannot be helped, it comes along with the positions of the nodes. If you wish to shift the grains up or down, then I suggest the following: after constructing the system with all nodes on the same Z level, then select a grain (e.g. to select grain number 3, use the option "-select prop grainID 3"), and shift it along Z with the option "-shift". You can repeat that for each grain to your convenience.

I must say that, if you encounter so many problems constructing your system, it mainly comes from the fact that it is highly unusual. It is extremely elongated (the Z dimension is very large compared to X and Y), which makes difficult the construction of a template of reasonable size; and grains have random rotations, meaning that the system cannot be periodic along Z. Such constraints make it very difficult for the algorithm to be efficient and produce nice-looking results. If you try with a box of increasing size, no matter how I modify the code, at some point you will find a size where the algorithm breaks down.

**Comment by jfikar** [comment]
Dear Pierre, thank you very much. 

(A) I've tried the very latest code and it seems you have added a useful memory check. For 2500A box on a 128MB RAM machine I now get:
```
X!X ERROR: memory (RAM) is insufficient to perform this operation.
           Try on a computer with more memory.
```
while 2000A seems to work fine and there are no missing atoms. Good job.

As for (B) I like your idea of shifting. It works. I only needed to change the file format from `lmp` to `cfg`. I think the `lmp` file does not contain grainID information, right? Is there an easy way to have grainID in the `lmp` file as well? It could be useful for imaging final configurations after lammps run.

With `lmp` atomsk gives a SIGSEGV

`atomsk poly.lmp -select prop grainID 8  -shift 0 0  0.8 tmp.lmp`

```
 >>> Opening the input file: poly.lmp
 ..> Input file was read successfully (133080 atoms).
 >>> Selecting atoms with grainID equal to 8.000.

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f2dad7e22da in ???
#1  0x7f2dad7e1503 in ???
#2  0x7f2dace47f1f in ???
#3  0x7f2dacec45d4 in ???
#4  0x55ef0cd7a150 in __select_MOD_select_xyz
	at /home/fik/atomsk-master/src/options/opt_select.f90:829
#5  0x55ef0cd9fe15 in __options_MOD_options_aff
	at /home/fik/atomsk-master/src/options/options.f90:1089
#6  0x55ef0cce4a2b in __mode_normal_MOD_convert_aff
	at /home/fik/atomsk-master/src/modes/mode_normal.f90:178
#7  0x55ef0cd15bf0 in __modes_MOD_run_mode
	at /home/fik/atomsk-master/src/modes/modes.f90:221
#8  0x55ef0ceb0cb4 in atomsk
	at /home/fik/atomsk-master/src/atomsk.f90:415
#9  0x55ef0ceb0dd9 in main
	at /home/fik/atomsk-master/src/atomsk.f90:46
./create: line 11:  5800 Segmentation fault      (core dumped) ~/bin/atomsk poly.lmp -select prop grainID 8 -shift 0 0 0.8 tmp.lmp
```

**Comment by pierrehirel** [comment]
Dear Sir,

Glad one of the problems was fixed.

Concerning LAMMPS data files (*.lmp), they do not allow to store additional properties (like grainID or others). This is not a limitation from Atomsk, but a limitation from the LAMMPS data file format (see LAMMPS documentation for more info).

If you want the final file to contain the grainID, write it into a file format that supports per-atom auxiliary properties. The most useful for this is Atomeye CFG format, which can be visualized by OVITO and is easy to manipulate.

Concerning the SIGSEV, I will try to reproduce the bug and fix it.

**Comment by pierrehirel** [comment]
Just fixed it, it was a but in option "-properties". Now the program should not SIGSEV anymore, but should report that the target property does not exist, as intended.

If that is all I think we can close this issue.

**Comment by jfikar** [comment]
Yes, the SIGSEV is fixed.
Thank you
